### ISSUE TITLE
Why does this use python?

### ISSUE THREAD

**Issue by drewrwilson** [nprapps/portland2#69]
I love this project and I've been playing with the code locally. I'm thinking through ways to use this as part of the ford-mozilla open web fellowship. I think that activist groups could use this tool or something very similar. Just like journalistic organizations, activist orgs are frequently needing to quickly make shareable images for social media. In fact sometimes it's activist org--as opposed to the publications themselves--who are the ones who really catapult stories into popularity.

A question: why does this uses python? Seems like the essential parts are js, css, html. I don't mean this question to sound like a criticism, I just want to understand the reasoning behind using python. Is there a technical reason? Or was it because those of you who worked on this were already very familiar with python? Or something else?

:balloon: Anyway, thanks for your work on this! :balloon:

**Comment by eads** [comment]
It's a good question. The main thing with something like this is having a good build process -- even though the output is js, css, and html, having templating, asset optimization, etc, makes development a lot easier. Since our team uses Python to build all our other projects, we used it here as well.
